# Generated by Django 5.2 on 2025-05-05 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='nome', help_text='Nome completo do paciente', max_length=255, verbose_name='Nome completo')),
                ('cpf', models.CharField(db_column='cpf', help_text='CPF com validação de formato e dígitos', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve estar no formato 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF')),
                ('data_nascimento', models.DateField(db_column='data_nascimento', verbose_name='Data de nascimento')),
                ('email', models.EmailField(db_column='email', error_messages={'unique': 'Já existe um paciente com este e-mail.'}, help_text='E-mail para contato', max_length=254, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(db_column='telefone', help_text='Número de telefone com DDD', max_length=15, validators=[django.core.validators.RegexValidator(message='Formato de telefone inválido.', regex='^\\(?\\d{2}\\)?[\\s-]?\\d{4,5}-?\\d{4}$')], verbose_name='Telefone com DDD')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, db_column='data_cadastro', help_text='Data de criação do cadastro', verbose_name='Data de cadastro')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['cpf'], name='idx_cpf'), models.Index(fields=['email'], name='idx_email')],
            },
        ),
    ]
