# Generated by Django 5.2 on 2025-05-05 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_column='data_consulta', verbose_name='Data da consulta')),
                ('hora', models.TimeField(db_column='hora_consulta', verbose_name='Hora da consulta')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('cancelada', 'Cancelada'), ('realizada', 'Realizada')], db_column='status_consulta', default='agendada', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_column='data_criacao', verbose_name='Data de criação')),
                ('medico', models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='medicos.medico', verbose_name='Médico')),
                ('paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'db_table': 'consulta',
                'ordering': ['data', 'hora'],
                'indexes': [models.Index(fields=['medico', 'data', 'hora'], name='idx_consulta_horario')],
                'unique_together': {('medico', 'data', 'hora')},
            },
        ),
    ]
